create database db_trabalho;
use db_trabalho;

drop table aluno;

create table aluno(
cod_aluno int primary key auto_increment,
ra_aluno int(11) not null,
nome_aluno varchar(50) not null,
tel_aluno int(11) not null,
email_aluno varchar(255) not null
);


create table especialidade(
cod_especialidade int(11) primary key auto_increment,
nome_especialidade varchar(50) not null
);

create table pais(
cod_pais int(11) primary key auto_increment,
nome_pais varchar(50) not null
);

create table fase_manutencao_prev(
cod_fase_manut_prev int(11) primary key auto_increment,
atividade_carie bit not null
);

create table etnia(
cod_etnia int(11) primary key auto_increment,
desc_etnia varchar(50) not null
);

create table estado_civil(
cod_estado_civil int(11) primary key auto_increment,
desc_estado_civil varchar(50) not null
);

create table turno(
cod_turno int(11) primary key auto_increment,
dia_semana varchar(50) not null,
horario time not null
);

create table avaliacao_oclusao(
cod_avaliacao_oclusao int(11) primary key auto_increment,
analise_sim_facial bit not null,
sobremordida int not null,
sobressaliencia int not null,
lado_direito int not null,
lado_esquerdo int not null,
mordida_cruzada int not null,
mordida_aberta bit not null,
desc_mordida_aberta varchar(255),
irrupcao_ectopica bit not null,
desc_irrupcao_ectopica varchar(255),
anquilose bit not null,
desc_anquilose varchar(255),
apinhamento bit not null,
desc_apinhamento varchar (255),
desgaste_incis_oclus bit not null,
desc_desg_incis_oclus varchar (255),
protusiva bit not null,
desc_protusiva varchar (255),
lateralidade_dir bit not null,
desc_lateralidade_dir varchar (255),
lateralidade_esq bit not null,
desc_lateralidade_esq varchar (255)
);

create table termo_consentimento(
cod_termo_consent int(11) primary key  auto_increment,
data_termo_consent date not null
);

create table aval_oclusao_ped_ad(
cod_aval_oclusao_ped_ad int(11) primary key  auto_increment,
denticao_decidua bit not null,
arco_tipo_i bit,
arco_tipo_ii bit,
arco_misto bit,
plano_reto bit,
degrau_distal bit,
degrau_mesial bit,
relacao_caninos int,
denticao_mista bit,
desc_denticao_mista bit,
denticao_permanente bit not null,
desc_denticao_perm int,
relacao_dentes_anta bit not null,
relacao_dentes_antb bit not null,
relacao_dentes_antc bit not null,
relacao_dentes_antd bit not null,
relacao_dentes_ante bit not null,
relacao_dentes_antf bit not null,
relacao_dentes_posta bit not null,
relacao_dentes_postb bit not null,
relacao_dentes_postc bit not null,
relacao_dentes_postd bit not null
);

create table termo_consent_ped_ad(
cod_termo_consent_ped_ad int(11) primary key auto_increment,
data_termo_consent_ped_ad date 
);

create table plano_tratamento(
cod_plano_tratamento int(11) primary key auto_increment,
alternativa1 varchar(500) not null,
alternativa3 varchar(500) not null,
alternativa2 varchar(500) not null,
custo_protese bit not null,
valor_protese float,
de_acordo bit not null,
data_autorizacao date not null
);

create table situacao_coroa_dental(
cod_sit_coroa_dental int primary key auto_increment,
coroa_integra bit not null,
restauracao bit not null,
lesao_cariosa bit not null,
desc_lesao_cariosa varchar(50),
abrasao bit not null,
protese_coroa_total bit not null,
exp_pulpar_carie bit not null,
exp_pulpar_acidental bit not null,
fratura_coronaria bit not null,
curativo bit not null,
protese_coroa_parcial bit not null,
reabsorcao_interna bit not null,
alteracao_cor bit not null,
ponte_fixa bit not null,
polipo_pulpar bit not null,
provisorio bit not null,
comp_face_ocl_inc bit not null,
comp_face_mesial bit not null,
comp_face_distal bit not null,
comp_face_lingual bit not null,
comp_face_vestibular bit not null
);

create table situacao_raizes_canais_rad(
cod_sit_raiz_canal_r int(11) primary key auto_increment,
artresia bit not null,
obturacao_deficiente bit not null,
calcificacao bit not null,
inst_fraturado bit not null,
reabsorcao_interna bit not null,
curvatura_acentuada bit not null,
rizogenese_incomp bit not null,
reabsorcao_apical bit not null,
canal_longo bit not null,
reabsorcao_externa bit not null,
fratura_radicular bit not null,
numero_raizes int(11)
);

create table situacao_tecido_suporte(
cod_sit_tecido_sup int(11) primary key auto_increment,
traumatismo_oclusal bit not null,
intrusao_dental bit not null,
bolsa_periodontal bit not null,
pericemento_esp bit not null,
envolvimento_furca bit not null,
avulsao_dental bit not null,
periodontite_apical bit not null,
ausencia_lamina_dura bit not null,
diagnostico varchar(50),
prognostico bit not null,
obs_adicionais varchar(255),
tratamento_indicado varchar(50)
);

create table professor(
cod_professor int(11) primary key auto_increment,
nome_professor varchar(50) not null,
email_professor varchar(255) not null,
tel_professor int(11) not null
);

create table exame_fis_intrab_simp(
cod_exame_fis_ib_s	int(11) primary key auto_increment,
dente11d	int(1),
dente11v	int(1),
dente11m	int(1),
dente11p	int(1),
dente12d	int(1),
dente12v	int(1),
dente12m	int(1),
dente12p	int(1),
dente13d	int(1),
dente13v	int(1),
dente13m	int(1),
dente13p	int(1),
dente14d	int(1),
dente14v	int(1),
dente14m	int(1),
dente14p	int(1),
dente15d	int(1),
dente15v	int(1),
dente15m	int(1),
dente15p	int(1),
dente16d	int(1),
dente16v	int(1),
dente16m	int(1),
dente16p	int(1),
dente17d	int(1),
dente17v	int(1),
dente17m	int(1),
dente17p	int(1),
dente18d	int(1),
dente18v	int(1),
dente18m	int(1),
dente18p	int(1),
dente21d	int(1),
dente21v	int(1),
dente21m	int(1),
dente21p	int(1),
dente22d	int(1),
dente22v	int(1),
dente22m	int(1),
dente22p	int(1),
dente23d	int(1),
dente23v	int(1),
dente23m	int(1),
dente23p	int(1),
dente24d	int(1),
dente24v	int(1),
dente24m	int(1),
dente24p	int(1),
dente25d	int(1),
dente25v	int(1),
dente25m	int(1),
dente25p	int(1),
dente26d	int(1),
dente26v	int(1),
dente26m	int(1),
dente26p	int(1),
dente27d	int(1),
dente27v	int(1),
dente27m	int(1),
dente27p	int(1),
dente28d	int(1),
dente28v	int(1),
dente28m	int(1),
dente28p	int(1),
dente31d	int(1),
dente31v	int(1),
dente31m	int(1),
dente31p	int(1),
dente32d	int(1),
dente32v	int(1),
dente32m	int(1),
dente32p	int(1),
dente33d	int(1),
dente33v	int(1),
dente33m	int(1),
dente33p	int(1),
dente34d	int(1),
dente34v	int(1),
dente34m	int(1),
dente34p	int(1),
dente35d	int(1),
dente35v	int(1),
dente35m	int(1),
dente35p	int(1),
dente36d	int(1),
dente36v	int(1),
dente36m	int(1),
dente36p	int(1),
dente37d	int(1),
dente37v	int(1),
dente37m	int(1),
dente37p	int(1),
dente38d	int(1),
dente38v	int(1),
dente38m	int(1),
dente38p	int(1),
dente41d	int(1),
dente41v	int(1),
dente41m	int(1),
dente41p	int(1),
dente42d	int(1),
dente42v	int(1),
dente42m	int(1),
dente42p	int(1),
dente43d	int(1),
dente43v	int(1),
dente43m	int(1),
dente43p	int(1),
dente44d	int(1),
dente44v	int(1),
dente44m	int(1),
dente44p	int(1),
dente45d	int(1),
dente45v	int(1),
dente45m	int(1),
dente45p	int(1),
dente46d	int(1),
dente46v	int(1),
dente46m	int(1),
dente46p	int(1),
dente47d	int(1),
dente47v	int(1),
dente47m	int(1),
dente47p	int(1),
dente48d	int(1),
dente48v	int(1),
dente48m	int(1),
dente48p	int(1),
porcentagem_ip int(3),
indice_psr1	int(1),
indice_psr2	int(1),
indice_psr3	int(1),
indice_psr4	int(1),
indice_psr5	int(1),
indice_psr6	int(1)
);

create table hist_pessoal_social(
cod_hist_pess_social int(11) primary key auto_increment,
pergunta1a bit not null,
pergunta1b bit not null,
pergunta1c bit not null,
pergunta1d bit not null,
pergunta1e bit not null,
pergunta1f bit not null,
pergunta2 bit not null,
pergunta3a bit not null,
pergunta3b bit not null,
pergunta3c bit not null,
pergunta3d bit not null,
pergunta4 varchar(50) not null,
pergunta5 varchar(50) not null,
pergunta6 bit not null,
pergunta7a bit not null,
pergunta7b bit not null,
pergunta8 varchar(50) not null,
pergunta9 varchar(50) not null,
pergunta10 bit,
pergunta11 bit not null,
pergunta12 varchar(50) not null,
pergunta13 bit not null,
pergunta14 varchar(50) not null,
pergunta15 bit not null,
pergunta16 varchar(50) ,
pergunta17 bit not null,
pergunta18 varchar(50),
pergunta19 int(2) not null
);

create table indice_higiene_oral(
cod_ind_hig_oral int(11) primary key auto_increment,
dente11_placa float not null,
dente11_calculo float not null,
dente31_placa float not null,
dente31_calculo float not null,
dente16_placa float not null,
dente16_calculo float not null,
dente26_placa float not null,
dente26_calculo float not null,
dente36_placa float not null,
dente36_calculo float not null,
dente46_placa float not null,
dente46_calculo float not null,
classificacao_ihos int(11) not null
);

create table exame_fisico(
cod_exame_fisico	int(11) primary key auto_increment,
facies	varchar(50) not null,
simetria_facial	bit not null,
edemas	varchar(255) not null,
pressao_arterial	varchar(255) not null,
pulso	int(11) not null,
temperatura	float not null,
parotideos	varchar(50) not null,
retrofaringeo	varchar(50) not null,
pre_auric	varchar(50) not null,
cervicais_ant	varchar(50) not null,
faciais	varchar(50) not null,
submentonianos	varchar(50) not null,
submandibulares	varchar(50) not null,
sublinguais	varchar(50) not null,
atm	varchar(255) not null,
labios	varchar(255) not null,
mucosa_jugal	varchar(255) not null,
palato	varchar(255) not null,
orofaringe	varchar(255) not null,
lingua	varchar(255) not null,
assoalho_boca	varchar(255) not null,
gengivas	varchar(255) not null,
dentes	varchar(255) not null,
rebordos_alveolares	varchar(255) not null,
freios_bridas	varchar(255) not null,
secrecao_salivar	varchar(255) not null,
ordenha_glandulas	varchar(255) not null,
higiene_bucal	varchar(255) not null,
oclusao	varchar(255) not null
);

create table doenca_atual(
cod_doenca_atual int(11) primary key auto_increment,
queixa_principal varchar(255) not null,
expectativa_tratamento varchar(255) not null,
hist_doenca_atual varchar(255) not null
);

create table teste_sensibilidade(
cod_teste_sensib int(11) primary key auto_increment,
teste_term_frio bit not null,
declinio_frio bit not null,
teste_term_quente bit not null,
declinio_quente bit not null,
teste_eletrico varchar(50),
palpacao_apical bit not null,
percussao_horizontal bit not null,
percussao_vertical bit not null
);

create table termo_consent_endondontico(
cod_t_cons_endondontico int(11) primary key auto_increment,
data_t_cons_endondontico date not null
);

create table tipo_tratamento(
cod_tipo_trat int(11) primary key auto_increment,
nome_tratamento varchar(50) not null,
desc_tratamento varchar(255) not null
);

create table gomo(
cod_gomo int(11) primary key auto_increment,
nome_gomo varchar(50) not null
);

create table box(
cod_box int(11) primary key auto_increment,
num_box int(11) not null,
cod_gomo int(11),
foreign key (cod_gomo) references gomo(cod_gomo)
);

create table hist_medico(
cod_hist_medico int(11) primary key auto_increment,
pergunta1 bit not null,
pergunta2 varchar(50) not null,
pergunta3 bit not null,
pergunta4 varchar(50) not null,
pergunta5 bit not null,
pergunta6 varchar(50) not null,
pergunta7 bit not null,
pergunta8 varchar(50) not null,
pergunta9 bit not null,
pergunta10 varchar(50) not null,
pergunta11 bit not null,
pergunta12 varchar(50) not null,
pergunta13 bit not null,
pergunta14 varchar(50) not null,
pergunta15 bit not null,
pergunta16 varchar(50) not null,
pergunta17 bit not null,
pergunta18 varchar(50) not null,
pergunta19 bit not null,
pergunta20 bit not null,
pergunta21 bit not null,
pergunta22 varchar(50) not null,
pergunta23 bit not null,
pergunta24 varchar(50) not null,
pergunta25 bit not null,
pergunta26 varchar(50) not null,
pergunta27 bit not null,
pergunta28 varchar(50) not null,
pergunta29 bit not null,
pergunta30 varchar(50) not null,
pergunta31 bit not null,
pergunta32 varchar(50) not null,
pergunta33 bit not null,
pergunta34 varchar(50) not null,
pergunta35 bit not null,
pergunta36 bit not null,
pergunta37 bit not null,
pergunta38 bit not null,
pergunta39 bit not null,
pergunta40 varchar(50) not null,
pergunta41 bit not null,
pergunta42 varchar(50) not null,
pergunta43 bit not null,
pergunta44 varchar(50) not null,
pergunta45 bit not null,
pergunta46 varchar(50) not null,
pergunta47 bit not null,
pergunta48 varchar(50) not null,
pergunta49 bit not null,
pergunta50 varchar(50) not null,
pergunta51 bit not null,
pergunta52 bit not null,
pergunta53 varchar(50) not null,
pergunta54 bit not null,
pergunta55 varchar(50) not null,
pergunta56 bit not null,
pergunta57 varchar(50) not null,
pergunta58 bit not null,
pergunta59 varchar(50) not null,
pergunta60 bit not null,
pergunta61 varchar(50) not null,
pergunta62 bit not null,
pergunta63 varchar(50) not null,
pergunta64 bit not null,
pergunta65 varchar(50) not null
);

create table hist_odontologica(
cod_hist_odontologica int(11) primary key auto_increment,
pergunta1 varchar(50) not null,
pergunta2 varchar(50) not null,
pergunta3 varchar(50) not null,
pergunta4 bit not null,
pergunta5 varchar(50) not null,
pergunta6 bit not null,
pergunta7 varchar(50),
pergunta8 bit not null,
pergunta9 varchar(50),
pergunta10 bit not null,
pergunta11 bit not null,
pergunta12 int(1) not null,
pergunta13 int(1) not null
);

create table exames_complem(
cod_exames_comp	int(11) primary key auto_increment,
desc_exame_radiograf	varchar(500) not null,
data_exame_radiograf	date not null,
desc_exame_hemat	varchar(500) not null,
data_exame_hemat	varchar(500) not null,
desc_outros_exames	varchar(500) not null,
diag_clinico_imag	varchar(500) not null,
diag_anatomo_pat	varchar(500) not null
);

create table responsavel(
cod_responsavel int(11) primary key auto_increment,
nome_responsavel varchar(50),
ocupacao_responsavel  varchar(255),
parentesco_responsavel  varchar(255)
);

create table ind_sangramento_gengival(
cod_ind_sang_gengival int(11) primary key auto_increment,
dente11d bit not null,
dente11v bit not null,
dente11m bit not null,
dente11p bit not null,
dente12d bit not null,
dente12v bit not null,
dente12m bit not null,
dente12p bit not null,
dente13d bit not null,
dente13v bit not null,
dente13m bit not null,
dente13p bit not null,
dente14d bit not null,
dente14v bit not null,
dente14m bit not null,
dente14p bit not null,
dente15d bit not null,
dente15v bit not null,
dente15m bit not null,
dente15p bit not null,
dente16d bit not null,
dente16v bit not null,
dente16m bit not null,
dente16p bit not null,
dente17d bit not null,
dente17v bit not null,
dente17m bit not null,
dente17p bit not null,
dente18d bit not null,
dente18v bit not null,
dente18m bit not null,
dente18p bit not null,
dente21d bit not null,
dente21v bit not null,
dente21m bit not null,
dente21p bit not null,
dente22d bit not null,
dente22v bit not null,
dente22m bit not null,
dente22p bit not null,
dente23d bit not null,
dente23v bit not null,
dente23m bit not null,
dente23p bit not null,
dente24d bit not null,
dente24v bit not null,
dente24m bit not null,
dente24p bit not null,
dente25d bit not null,
dente25v bit not null,
dente25m bit not null,
dente25p bit not null,
dente26d bit not null,
dente26v bit not null,
dente26m bit not null,
dente26p bit not null,
dente27d bit not null,
dente27v bit not null,
dente27m bit not null,
dente27p bit not null,
dente28d bit not null,
dente28v bit not null,
dente28m bit not null,
dente28p bit not null,
dente31d bit not null,
dente31v bit not null,
dente31m bit not null,
dente31p bit not null,
dente32d bit not null,
dente32v bit not null,
dente32m bit not null,
dente32p bit not null,
dente33d bit not null,
dente33v bit not null,
dente33m bit not null,
dente33p bit not null,
dente34d bit not null,
dente34v bit not null,
dente34m bit not null,
dente34p bit not null,
dente35d bit not null,
dente35v bit not null,
dente35m bit not null,
dente35p bit not null,
dente36d bit not null,
dente36v bit not null,
dente36m bit not null,
dente36p bit not null,
dente37d bit not null,
dente37v bit not null,
dente37m bit not null,
dente37p bit not null,
dente38d bit not null,
dente38v bit not null,
dente38m bit not null,
dente38p bit not null,
dente41d bit not null,
dente41v bit not null,
dente41m bit not null,
dente41p bit not null,
dente42d bit not null,
dente42v bit not null,
dente42m bit not null,
dente42p bit not null,
dente43d bit not null,
dente43v bit not null,
dente43m bit not null,
dente43p bit not null,
dente44d bit not null,
dente44v bit not null,
dente44m bit not null,
dente44p bit not null,
dente45d bit not null,
dente45v bit not null,
dente45m bit not null,
dente45p bit not null,
dente46d bit not null,
dente46v bit not null,
dente46m bit not null,
dente46p bit not null,
dente47d bit not null,
dente47v bit not null,
dente47m bit not null,
dente47p bit not null,
dente48d bit not null,
dente48v bit not null,
dente48m bit not null,
dente48p bit not null,
dente51d bit not null,
dente51v bit not null,
dente51m bit not null,
dente51p bit not null,
dente52d bit not null,
dente52v bit not null,
dente52m bit not null,
dente52p bit not null,
dente53d bit not null,
dente53v bit not null,
dente53m bit not null,
dente53p bit not null,
dente54d bit not null,
dente54v bit not null,
dente54m bit not null,
dente54p bit not null,
dente55d bit not null,
dente55v bit not null,
dente55m bit not null,
dente55p bit not null,
dente61d bit not null,
dente61v bit not null,
dente61m bit not null,
dente61p bit not null,
dente62d bit not null,
dente62v bit not null,
dente62m bit not null,
dente62p bit not null,
dente63d bit not null,
dente63v bit not null,
dente63m bit not null,
dente63p bit not null,
dente64d bit not null,
dente64v bit not null,
dente64m bit not null,
dente64p bit not null,
dente65d bit not null,
dente65v bit not null,
dente65m bit not null,
dente65p bit not null,
dente71d bit not null,
dente71v bit not null,
dente71m bit not null,
dente71p bit not null,
dente72d bit not null,
dente72v bit not null,
dente72m bit not null,
dente72p bit not null,
dente73d bit not null,
dente73v bit not null,
dente73m bit not null,
dente73p bit not null,
dente74d bit not null,
dente74v bit not null,
dente74m bit not null,
dente74p bit not null,
dente75d bit not null,
dente75v bit not null,
dente75m bit not null,
dente75p bit not null,
dente81d bit not null,
dente81v bit not null,
dente81m bit not null,
dente81p bit not null,
dente82d bit not null,
dente82v bit not null,
dente82m bit not null,
dente82p bit not null,
dente83d bit not null,
dente83v bit not null,
dente83m bit not null,
dente83p bit not null,
dente84d bit not null,
dente84v bit not null,
dente84m bit not null,
dente84p bit not null,
dente85d bit not null,
dente85v bit not null,
dente85m bit not null,
dente85p bit not null,
classificacao_isg int(11) not null
);


create table estado(
cod_estado int(11) primary key auto_increment,
nome_estado varchar(50) not null,
sigla_estado char(2) not null,
cod_pais int,
foreign key (cod_pais) references pais(cod_pais)
);

create table cidade(
cod_cidade int(11) primary key auto_increment,
nome_cidade varchar(50) not null,
cod_estado int,
foreign key (cod_estado) references estado(cod_estado)
);

create table prof_especialidade(
cod_prof_especialidade int(11) primary key auto_increment,
cod_professor int,
cod_especialidade int,
foreign key (cod_professor) references professor(cod_professor),
foreign key (cod_especialidade) references especialidade(cod_especialidade)
);

create table paciente(
cod_paciente int(11) primary key auto_increment,
nome_paciente varchar(50) not null,
apelido_paciente varchar(50),
cod_responsavel int(11),
foreign key (cod_responsavel) references responsavel(cod_responsavel),
cpf_paciente int(11),
rg_paciente varchar(20) not null,
orgao_expedidor_rg varchar(20) not null,
data_nasc_paciente date not null,
cod_cidade int(11),
foreign key (cod_cidade) references cidade(cod_cidade),
cod_pais int(11),
foreign key (cod_pais) references pais(cod_pais),
email_paciente varchar(255) not null,
necess_especial bit not null,
sexo_paciente char(1) not null,
peso_paciente float,
nome_pai varchar(50),
nome_mae varchar(50) not null,
ocupacao_paciente varchar(50),
cod_etnia int not null,
foreign key (cod_etnia) references etnia(cod_etnia),
cod_estado_civil int,
foreign key (cod_estado_civil) references estado_civil(cod_estado_civil),
encaminhado_por int not null,
desc_encamin_por varchar(50),
nome_contato_emerg varchar(50),
tel_contato_emer int(11) not null
);

create table endereco(
cod_endereco int(11) primary key auto_increment,
cod_paciente int(11),
foreign key (cod_paciente) references paciente(cod_paciente),
cod_cidade int(11),
foreign key (cod_cidade) references cidade(cod_cidade),
logradouro varchar(50) not null,
complemento varchar(50) not null,
num_endereco int(11) not null,
cep int(11) not null,
zona_rural bit not null,
endereco_comercial bit not null
);

create table telefone_paciente(
cod_tel_paciente int(11) primary key auto_increment,
cod_paciente int(11),
foreign key (cod_paciente) references paciente(cod_paciente),
telefone_paciente int(11) not null,
tel_comercial bit not null
);

create table grupo_aluno(
cod_grupo_aluno int(11) primary key auto_increment,
cod_turno int(11),
foreign key (cod_turno) references turno(cod_turno),
cod_box int(11),
foreign key (cod_box) references box(cod_box),
cod_professor int(11),
foreign key (cod_professor) references professor(cod_professor)
);

create table aluno_especialidade (
cod_aluno_espec	int(11) primary key auto_increment,
cod_aluno 	int(11),
foreign key (cod_aluno) references aluno(cod_aluno),
cod_especialidade	int(11),
foreign key (cod_especialidade) references especialidade(cod_especialidade),
cod_grupo_aluno	int(11),
foreign key (cod_grupo_aluno) references grupo_aluno(cod_grupo_aluno),
semestre	int(5)
);

create table prontuario_pediatria(
cod_prontuario_ped int(11) primary key auto_increment,
reside_com1 bit not null,
reside_com2 bit not null,
reside_com3 bit not null,
reside_com4 bit not null,
desc_reside_com varchar(50),
irmaos bit not null,
qtd_irmaos int(11) not null,
pergunta1 bit not null,
desc_pergunta1 varchar(50),
pergunta2 bit not null,
desc_pergunta2 varchar(50),
pergunta3 bit not null,
desc_pergunta3 varchar(50),
pergunta4 bit not null,
desc_pergunta4 varchar(50),
pergunta5 bit not null,
desc_pergunta5 varchar(50),
pergunta6 bit not null,
desc_pergunta6 varchar(50),
pergunta7 bit not null,
desc_pergunta7 varchar(50),
pergunta8a bit not null,
pergunta8b bit not null,
pergunta8c bit not null,
pergunta8d bit not null,
pergunta8e bit not null,
pergunta8f bit not null,
pergunta8g bit not null,
desc_pergunta8 varchar(50) not null,
pergunta9 bit not null,
desc_pergunta9 varchar(50),
pergunta10 bit not null,
pergunta11 bit not null,
desc_pergunta11 varchar(50),
pergunta12 bit not null,
pergunta13 bit not null,
desc_pergunta13 varchar(50),
pergunta14 int(11) not null,
desc_pergunta14 varchar(50),
pergunta15a bit not null,
pergunta15b bit not null,
pergunta15c bit not null,
pergunta15d bit not null,
desc_pergunta15 varchar(50),
pergunta16 int(11) not null,
pergunta17 int(11) not null,
desc_pergunta17 varchar(50),
pergunta18 varchar(50) not null,
pergunta19 bit not null,
pergunta20 bit not null,
desc_pergunta20 varchar(50),
pergunta21a bit not null,
pergunta21b bit not null,
pergunta21c bit not null,
pergunta21d bit not null,
desc_pergunta21 varchar(50),
pergunta22 bit not null,
desc_pergunta22 varchar(50),
pergunta23a bit not null,
pergunta23b bit not null,
pergunta24 bit not null,
desc_pergunta24 varchar(50),
pergunta25 varchar(50) not null,
pergunta26 varchar(50) not null,
pergunta27 int(11) not null,
pergunta28a bit not null,
pergunta28b bit not null,
pergunta28c bit not null,
pergunta28d bit not null,
pergunta28e bit not null,
pergunta28f bit not null,
pergunta28g bit not null,
pergunta28h bit not null,
pergunta28i int not null,
pergunta29 bit not null,
desc_pergunta29 varchar(50),
pergunta30 int not null,
pergunta31 bit not null,
desc_pergunta31 varchar(50),
pergunta32 bit not null,
pergunta33a int not null,
pergunta33b bit not null,
pergunta33c int,
pergunta33d bit not null,
pergunta33e bit not null,
pergunta33f int,
pergunta33g bit ,
pergunta33h varchar(50),
pergunta34 bit not null,
pergunta35a bit not null,
pergunta35b bit not null,
pergunta35c bit not null,
pergunta35d bit not null,
pergunta36 bit not null,
desc_pergunta36 varchar(50) not null,
pergunta37a bit not null,
pergunta37b bit,
pergunta37c bit,
pergunta37d bit,
pergunta37e bit,
pergunta37f bit,
pergunta37g bit,
pergunta37h bit,
pergunta37i bit,
pergunta37j bit,
pergunta37k bit,
pergunta37l bit,
pergunta37m bit,
desc_pergunta37 varchar(50),
pergunta38 bit not null,
desc_pergunta38 varchar(50),
pergunta39 bit,
desc_pergunta39 varchar(50),
pergunta40 bit,
pergunta41 bit not null,
desc_pergunta41 varchar(50),
pergunta42a bit not null,
pergunta42b bit not null,
pergunta42c bit not null,
pergunta42d bit not null,
pergunta42e bit not null,
pergunta42f bit not null,
pergunta42g bit not null,
pergunta42h bit not null,
pergunta42i bit not null,
pergunta42j bit not null,
pergunta42k bit not null,
pergunta42l bit not null,
pergunta42m bit not null,
desc_pergunta42 varchar(50),
pergunta43 bit not null,
desc_pergunta43 varchar(50),
pergunta44 bit not null,
pergunta45a bit not null,
pergunta45b bit not null,
pergunta45c bit not null,
pergunta45d bit not null,
desc_pergunta45 varchar(50),
pergunta46 bit not null,
pergunta47 bit not null,
desc_pergunta47 varchar(50),
pergunta48 bit not null,
desc_pergunta48 varchar(50),
pergunta49 bit not null,
desc_pergunta49 varchar(50),
pergunta50 bit not null,
desc_pergunta50 varchar(50),
pergunta51 bit not null,
desc_pergunta51 varchar(50),
pergunta52 bit not null,
desc_pergunta52 varchar(50),
pergunta53 bit not null,
desc_pergunta53 varchar(50),
pergunta54 bit not null,
desc_pergunta54 varchar(50),
pergunta55 bit not null,
desc_pergunta55 varchar(50),
pergunta56 bit not null,
desc_pergunta56 varchar(50),
pergunta57 bit not null,
desc_pergunta57 varchar(50),
pergunta58 bit not null,
desc_pergunta58 varchar(50),
pergunta59 bit not null,
desc_pergunta59 varchar(50),
plano_tratamento VARCHAR(999)
);

ALTER TABLE prontuario_pediatria 
    ADD COLUMN cod_paciente INT(11),
    ADD COLUMN cod_grupo_aluno INT(11),
    ADD COLUMN cod_aval_oclusao_ped_ad INT(11),
    ADD COLUMN cod_ind_hig_oral INT(11),
    ADD COLUMN cod_fase_manut_prev INT(11),
    ADD COLUMN cod_termo_consent_ped_ad INT(11),
    ADD FOREIGN KEY (cod_paciente) REFERENCES paciente(cod_paciente),
    ADD FOREIGN KEY (cod_grupo_aluno) REFERENCES grupo_aluno(cod_grupo_aluno),
    ADD FOREIGN KEY (cod_aval_oclusao_ped_ad) REFERENCES aval_oclusao_ped_ad(cod_aval_oclusao_ped_ad),
    ADD FOREIGN KEY (cod_ind_hig_oral) REFERENCES indice_higiene_oral(cod_ind_hig_oral),
    ADD FOREIGN KEY (cod_fase_manut_prev) REFERENCES fase_manutencao_prev(cod_fase_manut_prev),
    ADD FOREIGN KEY (cod_termo_consent_ped_ad) REFERENCES termo_consent_ped_ad(cod_termo_consent_ped_ad);

create table prontuario(
cod_prontuario	int(11) primary key auto_increment,
cod_paciente	int(11),
FOREIGN KEY (cod_paciente) REFERENCES paciente(cod_paciente),
cod_grupo_aluno	int(11),
FOREIGN KEY (cod_grupo_aluno) REFERENCES grupo_aluno(cod_grupo_aluno),
cod_doenca_atual	int(11),
foreign key (cod_doenca_atual) references doenca_atual(cod_doenca_atual),
cod_hist_medico	int(11),
FOREIGN KEY (cod_hist_medico) REFERENCES hist_medico(cod_hist_medico),
historia_familiar	varchar(255),
cod_hist_pess_social	int(11),
FOREIGN KEY (cod_hist_pess_social) REFERENCES hist_pessoal_social(cod_hist_pess_social),
cod_hist_odontologica	int(11),
FOREIGN KEY (cod_hist_odontologica) REFERENCES hist_odontologica(cod_hist_odontologica),
cod_exame_fis_ib_s	int(11),
FOREIGN KEY (cod_exame_fis_ib_s) REFERENCES exame_fis_intrab_simp(cod_exame_fis_ib_s),
cod_avaliacao_oclusao	int(11),
FOREIGN KEY (cod_avaliacao_oclusao) REFERENCES avaliacao_oclusao(cod_avaliacao_oclusao),
cod_exame_fisico	int(11),
FOREIGN KEY (cod_exame_fisico) REFERENCES exame_fisico(cod_exame_fisico),
cod_exames_comp	int(11),
FOREIGN KEY (cod_exames_comp) REFERENCES exames_complem(cod_exames_comp),
cod_plano_tratamento	int(11),
FOREIGN KEY (cod_plano_tratamento) REFERENCES plano_tratamento(cod_plano_tratamento),
cod_termo_consent	int(11),
FOREIGN KEY (cod_termo_consent) REFERENCES termo_consentimento(cod_termo_consent)
);

create table receituario(
cod_receituario	int(11) primary key auto_increment,
cod_paciente	int(11),
foreign key (cod_paciente) references paciente(cod_paciente),
cod_grupo_aluno	int(11),
foreign key (cod_grupo_aluno) references grupo_aluno(cod_grupo_aluno),
desc_receituario	varchar(255) not null,
data_receituario	date not null
);

create table formulario_referencia (
    cod_form_ref int(11) primary key auto_increment,
    cod_paciente int(11) not null,
    cod_grupo_aluno int(11) not null,
    cod_especialid_origem int(11) not null,
    cod_especialid_destino int(11) not null,
    tratamento_executado varchar(255) not null,
    data_formulario_ref date not null,
    data_reavaliacao date not null,
    pergunta1 bit not null,
    pergunta2 bit not null,
    pergunta3 bit not null,
    pergunta4 bit not null,
    pergunta5 bit not null,
    pergunta6 bit not null,
    pergunta7 bit not null,
    pergunta8 bit not null,
    pergunta9 bit not null,
    pergunta10 bit not null,
    pergunta11 bit not null,
    pergunta12 bit not null,
    pergunta13 bit not null,
    pergunta14 bit not null,
    pergunta15 bit not null,
    pergunta16 bit not null,
    pergunta17 bit not null,
    pergunta18 bit not null,
    pergunta19 bit not null,
    pergunta20 bit not null,
    pergunta21 bit not null,
    pergunta22 bit not null,
    pergunta23 bit not null,
    foreign key (cod_paciente) references paciente(cod_paciente),
    foreign key (cod_grupo_aluno) references grupo_aluno(cod_grupo_aluno),
    foreign key (cod_especialid_origem) references especialidade(cod_especialidade),
    foreign key (cod_especialid_destino) references especialidade(cod_especialidade)
);

create table atestado_acompanhamento (
    cod_atest_acomp int(11) primary key auto_increment,
    cod_paciente int(11),
    cod_grupo_aluno int(11),
    nome_acompanhante varchar(50) not null,
    horario_inicio time not null,
    horario_fim time not null,
    data_atest_acomp date not null,
    foreign key (cod_paciente) references paciente(cod_paciente),
    foreign key (cod_grupo_aluno) references grupo_aluno(cod_grupo_aluno)
);

create table termo_concordancia (
    cod_termo_concord int(11) primary key auto_increment,
    cod_paciente int(11),
    data_termo_concord date not null,
    foreign key (cod_paciente) references paciente(cod_paciente)
);

create table prontuario_adolescente (
    cod_prontuario_adol int(11) primary key auto_increment,
    reside_com1 bit not null,
    reside_com2 bit not null,
    reside_com3 bit not null,
    desc_reside_com_opic varchar(50),
    irmaos bit not null,
    qtd_irmaos int(11),
    pergunta1 bit not null,
    desc_pergunta1_opic varchar(50),
    pergunta2 bit not null,
    desc_pergunta2_opic varchar(50),
    pergunta3 bit not null,
    desc_pergunta3_opic varchar(50),
    pergunta4 bit not null,
    desc_pergunta4_opic varchar(50),
    pergunta5 bit not null,
    desc_pergunta5_opic varchar(50),
    pergunta6 bit not null,
    desc_pergunta6_opic varchar(50),
    pergunta7 bit not null,
    desc_pergunta7_opic varchar(50),
    pergunta8a bit not null,
    pergunta8b bit not null,
    pergunta8c bit not null,
    pergunta8d bit not null,
    pergunta8e bit not null,
    pergunta8f bit not null,
    pergunta8g bit not null,
    desc_pergunta8 varchar(50),
    pergunta9 bit not null,
    desc_pergunta9_opic varchar(50),
    pergunta10 int,
    pergunta11 bit not null,
    desc_pergunta11_opic varchar(50),
    pergunta12 varchar(50),
    pergunta13 bit not null,
    pergunta14 bit not null,
    desc_pergunta14_opic varchar(50),
    pergunta15a bit not null,
    pergunta15b bit not null,
    pergunta15c bit not null,
    pergunta15d bit not null,
    desc_pergunta15_opic varchar(50),
    pergunta16 bit not null,
    desc_pergunta16_opic varchar(50),
    pergunta17a bit not null,
    pergunta17b bit not null,
    pergunta18 bit not null,
    desc_pergunta18_opic varchar(50),
    pergunta19 varchar(50),
    pergunta20 varchar(50),
    pergunta21 int,
    pergunta22 bit not null,
    pergunta23 bit not null,
    desc_pergunta23_opic varchar(50),
    pergunta24a bit not null,
    pergunta24b bit not null,
    pergunta24c bit not null,
    pergunta24d bit not null,
    pergunta24e bit not null,
    pergunta24f bit not null,
    pergunta24g bit not null,
    pergunta24h bit not null,
    pergunta24i bit not null,
    pergunta24j bit not null,
    pergunta24k bit not null,
    pergunta24l bit not null,
    pergunta24m bit not null,
    desc_pergunta24_opic varchar(50),
    pergunta25 varchar(50),
    pergunta26 bit not null,
    pergunta27a bit not null,
    pergunta27b bit not null,
    pergunta27c bit not null,
    pergunta27d bit not null,
    desc_pergunta27_opic varchar(50),
    pergunta28 bit not null,
    pergunta29 bit not null,
    desc_pergunta29_opic varchar(50),
    pergunta30 bit not null,
    desc_pergunta30_opic varchar(50),
    pergunta31 bit not null,
    desc_pergunta31_opic varchar(50),
    pergunta32 bit not null,
    desc_pergunta32_opic varchar(50),
    pergunta33 bit not null,
    desc_pergunta33_opic varchar(50),
    pergunta34 bit not null,
    desc_pergunta34_opic varchar(50),
    pergunta35 bit not null,
    desc_pergunta35_opic varchar(50),
    pergunta36 bit not null,
    desc_pergunta36_opic varchar(50),
    pergunta37 bit not null,
    desc_pergunta37_opic varchar(50),
    pergunta38 bit not null,
    desc_pergunta38_opic varchar(50),
    pergunta39 bit not null,
    desc_pergunta39_opic varchar(50),
    pergunta40 bit not null,
    desc_pergunta40_opic varchar(50),
    pergunta41 bit not null,
    desc_pergunta41_opic varchar(50),
	cod_paciente int(11),
    cod_grupo_aluno int(11),
    cod_aval_oclusao_ped_ad int(11),
    cod_ind_hig_oral int(11),
    cod_ind_sang_gengival int(11),
    plano_tratamento varchar(999),
    cod_fase_manut_prev int(11),
    cod_termo_consent_ped_ad int(11),
    foreign key (cod_paciente) references paciente(cod_paciente),
    foreign key (cod_grupo_aluno) references grupo_aluno(cod_grupo_aluno),
    foreign key (cod_aval_oclusao_ped_ad) references aval_oclusao_ped_ad(cod_aval_oclusao_ped_ad),
    foreign key (cod_ind_hig_oral) references indice_higiene_oral(cod_ind_hig_oral),
    foreign key (cod_ind_sang_gengival) references ind_sangramento_gengival(cod_ind_sang_gengival),
    foreign key (cod_fase_manut_prev) references fase_manutencao_prev(cod_fase_manut_prev),
    foreign key (cod_termo_consent_ped_ad) references termo_consent_ped_ad(cod_termo_consent_ped_ad)
);

create table controle_atendimento (
    cod_controle_atend int(11) primary key auto_increment,
    cod_prontuario int(11),
    cod_prontuario_ped int(11),
    cod_prontuario_adol int(11),
    cod_grupo_aluno int(11),
    desc_controle_atend varchar(255) not null,
    data_controle_atend date not null,
    data_retorno_controle date not null,
    foreign key (cod_prontuario) references prontuario(cod_prontuario),
    foreign key (cod_prontuario_ped) references prontuario_pediatria(cod_prontuario_ped),
    foreign key (cod_prontuario_adol) references prontuario_adolescente(cod_prontuario_adol),
    foreign key (cod_grupo_aluno) references grupo_aluno(cod_grupo_aluno)
);

create table periograma (
    cod_periograma int(11) primary key auto_increment,
    cod_prontuario int(11),
    cod_prontuario_ped int(11),
    cod_prontuario_adol int(11),
    data_periograma date not null,
    foreign key (cod_prontuario) references prontuario(cod_prontuario),
    foreign key (cod_prontuario_ped) references prontuario_pediatria(cod_prontuario_ped),
    foreign key (cod_prontuario_adol) references prontuario_adolescente(cod_prontuario_adol)
);


create table dente_periograma (
    cod_dente_periograma int(11) primary key auto_increment,
    cod_periograma int(11),
    nro_dente_periograma int not null,
    mobilidade int not null,
    furca int not null,
    foreign key (cod_periograma) references periograma(cod_periograma)
);

create table medida_dente (
    cod_medida_dente int(11) primary key auto_increment,
    cod_dente_periograma int(11),
    posicao_medida varchar(50) not null,
    sangramento bit not null not null,
    profund_gengiva float not null,
    profund_sondagem float not null,
    nivel_insercao float not null,
    foreign key (cod_dente_periograma) references dente_periograma(cod_dente_periograma)
);

create table odontograma (
    cod_odontograma int(11) primary key auto_increment,
    cod_prontuario int(11),
    cod_prontuario_ped int(11),
    cod_prontuario_adol int(11),
    
    dente11a int(1), dente11b int(1), dente11c int(1), dente11d int(1), dente11e int(1),
    dente12a int(1), dente12b int(1), dente12c int(1), dente12d int(1), dente12e int(1),
    dente13a int(1), dente13b int(1), dente13c int(1), dente13d int(1), dente13e int(1),
    dente14a int(1), dente14b int(1), dente14c int(1), dente14d int(1), dente14e int(1),
    dente15a int(1), dente15b int(1), dente15c int(1), dente15d int(1), dente15e int(1),
    dente16a int(1), dente16b int(1), dente16c int(1), dente16d int(1), dente16e int(1),
    dente17a int(1), dente17b int(1), dente17c int(1), dente17d int(1), dente17e int(1),
    dente18a int(1), dente18b int(1), dente18c int(1), dente18d int(1), dente18e int(1),
    dente21a int(1), dente21b int(1), dente21c int(1), dente21d int(1), dente21e int(1),
    dente22a int(1), dente22b int(1), dente22c int(1), dente22d int(1), dente22e int(1),
    dente23a int(1), dente23b int(1), dente23c int(1), dente23d int(1), dente23e int(1),
    dente24a int(1), dente24b int(1), dente24c int(1), dente24d int(1), dente24e int(1),
    dente25a int(1), dente25b int(1), dente25c int(1), dente25d int(1), dente25e int(1),
    dente26a int(1), dente26b int(1), dente26c int(1), dente26d int(1), dente26e int(1),
    dente27a int(1), dente27b int(1), dente27c int(1), dente27d int(1), dente27e int(1),
    dente28a int(1), dente28b int(1), dente28c int(1), dente28d int(1), dente28e int(1),
    
    dente31a int(1), dente31b int(1), dente31c int(1), dente31d int(1), dente31e int(1),
    dente32a int(1), dente32b int(1), dente32c int(1), dente32d int(1), dente32e int(1),
    dente33a int(1), dente33b int(1), dente33c int(1), dente33d int(1), dente33e int(1),
    dente34a int(1), dente34b int(1), dente34c int(1), dente34d int(1), dente34e int(1),
    dente35a int(1), dente35b int(1), dente35c int(1), dente35d int(1), dente35e int(1),
    dente36a int(1), dente36b int(1), dente36c int(1), dente36d int(1), dente36e int(1),
    dente37a int(1), dente37b int(1), dente37c int(1), dente37d int(1), dente37e int(1),
    dente38a int(1), dente38b int(1), dente38c int(1), dente38d int(1), dente38e int(1),
    dente41a int(1), dente41b int(1), dente41c int(1), dente41d int(1), dente41e int(1),
    dente42a int(1), dente42b int(1), dente42c int(1), dente42d int(1), dente42e int(1),
    dente43a int(1), dente43b int(1), dente43c int(1), dente43d int(1), dente43e int(1),
    dente44a int(1), dente44b int(1), dente44c int(1), dente44d int(1), dente44e int(1),
    dente45a int(1), dente45b int(1), dente45c int(1), dente45d int(1), dente45e int(1),
    dente46a int(1), dente46b int(1), dente46c int(1), dente46d int(1), dente46e int(1),
    dente47a int(1), dente47b int(1), dente47c int(1), dente47d int(1), dente47e int(1),
    dente48a int(1), dente48b int(1), dente48c int(1), dente48d int(1), dente48e int(1),
       
    dente51a int(1), dente51b int(1), dente51c int(1), dente51d int(1), dente51e int(1),
    dente52a int(1), dente52b int(1), dente52c int(1), dente52d int(1), dente52e int(1),
    dente53a int(1), dente53b int(1), dente53c int(1), dente53d int(1), dente53e int(1),
    dente54a int(1), dente54b int(1), dente54c int(1), dente54d int(1), dente54e int(1),
    dente55a int(1), dente55b int(1), dente55c int(1), dente55d int(1), dente55e int(1),
    dente61a int(1), dente61b int(1), dente61c int(1), dente61d int(1), dente61e int(1),
    dente62a int(1), dente62b int(1), dente62c int(1), dente62d int(1), dente62e int(1),
    dente63a int(1), dente63b int(1), dente63c int(1), dente63d int(1), dente63e int(1),
    dente64a int(1), dente64b int(1), dente64c int(1), dente64d int(1), dente64e int(1),
    dente65a int(1), dente65b int(1), dente65c int(1), dente65d int(1), dente65e int(1),
    dente71a int(1), dente71b int(1), dente71c int(1), dente71d int(1), dente71e int(1),
    dente72a int(1), dente72b int(1), dente72c int(1), dente72d int(1), dente72e int(1),
    dente73a int(1), dente73b int(1), dente73c int(1), dente73d int(1), dente73e int(1),
    dente74a int(1), dente74b int(1), dente74c int(1), dente74d int(1), dente74e int(1),
    dente75a int(1), dente75b int(1), dente75c int(1), dente75d int(1), dente75e int(1),
	dente81a int(1), dente81b int(1), dente81c int(1), dente81d int(1), dente81e int(1),
    dente82a int(1), dente82b int(1), dente82c int(1), dente82d int(1), dente82e int(1),
    dente83a int(1), dente83b int(1), dente83c int(1), dente83d int(1), dente83e int(1),
    dente84a int(1), dente84b int(1), dente84c int(1), dente84d int(1), dente84e int(1),
    dente85a int(1), dente85b int(1), dente85c int(1), dente85d int(1), dente85e int(1)
);

create table ficha_endodontica (
    cod_ficha_endodontica int(11) primary key auto_increment,
    cod_paciente int(11),
    cod_grupo_aluno int(11),
    cod_sit_coroa_dental int(11),
    cod_sit_raiz_canal_r int(11),
    cod_sit_tecido_sup int(11),
    cod_teste_sensib int(11),
    cod_t_cons_endondontico int(11),
    foreign key (cod_paciente) references paciente(cod_paciente),
    foreign key (cod_grupo_aluno) references grupo_aluno(cod_grupo_aluno),
    foreign key (cod_sit_coroa_dental) references situacao_coroa_dental(cod_sit_coroa_dental),
    foreign key (cod_sit_raiz_canal_r) references situacao_raizes_canais_rad(cod_sit_raiz_canal_r),
    foreign key (cod_sit_tecido_sup) references situacao_tecido_suporte(cod_sit_tecido_sup),
    foreign key (cod_teste_sensib) references teste_sensibilidade(cod_teste_sensib),
    foreign key (cod_t_cons_endondontico) references termo_consent_endondontico(cod_t_cons_endondontico)
);

create table proc_real_endod (
    cod_proc_real_endod int(11) primary key auto_increment,
    cod_ficha_endodontica int(11) not null,
    data_proc_real_endod date not null,
    diagnostico_clinico int not null,
    nro_dente int not null,
    nro_grampo int not null,
    periodontite_apical bit not null,
    desc_canal varchar(50) not null,
    referencia varchar(50) not null,
    cdr varchar(50) not null,
    cpc varchar(50) not null,
    ct float not null,
    ti varchar(50) not null,
    obturacao varchar(50) not null,
    subs_utilizadas1 bit not null,
    subs_utilizadas2 bit not null,
    subs_utilizadas3 bit not null,
    subs_utilizadas4 bit not null,
    subs_utilizadas5 bit not null,
    subs_utilizadas6 bit not null,
    med_curativa_utiliz1 bit not null,
    med_curativa_utiliz2 bit not null,
    med_curativa_utiliz3 bit not null,
    med_curativa_utiliz4 bit not null,
    desc_med_curativa varchar(50),
    instr_manual bit not null,
    desc_instr_manual varchar(50),
    instr_rotatoria bit not null,
    desc_instr_rotatoria varchar(50),
    cimento_obturador varchar(50) not null,
    cones_utilizados varchar(50) not null,
    cont_rad_imed1 bit not null,
    cont_rad_imed2 bit not null,
    cont_rad_imed3 bit not null,
    cont_rad_imed4 bit not null,
    cont_rad_imed5 bit not null,
    desc_cont_rad_imed5 varchar(50),
    cont_rad_imed6 bit not null,
    cont_rad_imed7 bit not null,
    desc_proc_real varchar(500) not null,
    foreign key (cod_ficha_endodontica) references ficha_endodontica(cod_ficha_endodontica)
);

create table agendamento (
    cod_gomo int(11) primary key auto_increment,
    cod_paciente int(11),
    cod_grupo_aluno int(11),
    data_agendamento date,
    hora_agendamento time,
    foreign key (cod_paciente) references paciente(cod_paciente),
    foreign key (cod_grupo_aluno) references grupo_aluno(cod_grupo_aluno)
);

create table atestado (
    cod_atestado int(11) primary key auto_increment,
    cod_paciente int(11),
    cod_grupo_aluno int(11),
    motivo_atestado varchar(50) not null,
    horario_inicio time not null,
    horario_fim time not null,
    tempo_reposo time not null,
    cid int(11) not null,
    data_atestado date not null,
    foreign key (cod_paciente) references paciente(cod_paciente),
    foreign key (cod_grupo_aluno) references grupo_aluno(cod_grupo_aluno)
);

create table termo_orientacao (
    cod_termo_orientacao int(11) primary key primary key,
    cod_aluno int(11),
    cod_professor int(11),
    data_termo_orient date not null,
    foreign key (cod_aluno) references aluno(cod_aluno),
    foreign key (cod_professor) references professor(cod_professor)
);



















